os: linux
dist: focal
language: java
jdk: openjdk17
cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: RtYwIpoE8ya5L6TOLfKRuV832eprycwm4hLO6LoO1EoIpsnTLe9WRZVXmwcn5K7KgPYYKJgJ4oG7vJ/SaIGX6eXIBpxVFIikLLtRevNUPMALNtHGLSrH+f5O8nur5GXc2Px7CWHKSzn5yD6ZJwB8y/QMQx8JIlhJjP1xvOxfzGOOuYiO0aKl6ASn2D0hzo72tCSDrf9zTi6G3pOKfw27tT9ARoJWsVEOOhcg/+ne9ok2aABN7fnis9t8PwYIJr3YZvNneA+8EEyTlhtMQ93YGF3PB41NxV8zd/9/0iUe3mJsUNFRAsDunmm25nlJfnZjSP5X+DETC188y/8T4YpbJTNYCzHDPs4uqRJUW2lsgt4H0WLio7enCx6dFTAwDdjltdXAoHLpX5oVZUvpoDB7dr44FtT6kABRkbAq9m4j1N6z1pDj/8EfBh73DLguccA8WeGiMoh4zVXWhz6JXoh1itv/6lqATbKybNMB3lT9S37G8DG+HM1R+31Nu1GDTNqWdE0KMGuWYMAU+rd7twIL7BIYu5iz0tpvcCvz+wMfFoAxi6tJPi/1jCjEI39SP2w32plHjtCuiSgz0kMykqxTga0B9FXKae1MzWCvKWxVs5igKKrSoRFyVvlmG/wwNIGP3f04f1GBlrk/Ns0LV6SU/+WCp5TGQqYSp3OrZbJv3mw=
script:
- mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_tsv-vcf-converter
deploy:
  provider: releases
  token:
    secure: RXogA5Cqpx3U5yRYUCrAq49eaVoUa98WaO567ia7XgkeSjXLHhbev3tL4LUQVJfGJfKl6bZ8lgXaez3jfnDANglpKg7HXoXUXBTYj1aIHyux6T7vNLcczv8aAJJnAiLZm8kQSPH3harV4FBXPlgUpD5ww8wWkShL6aCB7mEZWxS0pyII983gKQz5Y02wiWQguKS/LgsvUMvlTmU4BKuxkNNVo4OrjwZMkRtiREEPipTXSnkVgYBHXrXZi+51IP8bnte9vGU8pAXtEAGgBGqWqujhITdMiHzvcmTAqGz908SOPOTAhaE4ewSc0U8bXiFRd/X/bGexLKT97xs7We/+jRU+4Wj/hz75GIUZyk3yDulHZssci9DqZUb7D4u7Hnh6XrUZNBwKIjGcWZPsIk0kWdpRg3e1caD25/JIze8eYMB1dDrEFtJ2Puv0saqY1bIQA1XDxNJMbgChxvPyk/apF/MnHnfmprrTIfO8nWt3kUVhq4RGphRwRxvkdE4Hoh/FZADgKdjNohmoJviJmMF5uvAuHZqc6/bLWTh2fU+rGBRNQDQ2DZZPbhf5BK175FaggeIIJJml596osgVX5OiTZYhyXQHIkv/X8lTTzWEbWvJ9TMBSuXoSQSzKXxZIImPGRBSr3aCEK2lZMxXiTioA4iG3vhu7EVPGEVhblDqLQgo=
  file: target/tsv-vcf-converter.jar
  prerelease: true
  on:
    tags: true
  edge: true
